# Generated by Django 4.2.3 on 2024-03-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('UP', 'Unprocessed'), ('CM', 'Completed'), ('FD', 'Failed')], default='UP', max_length=2),
        ),
    ]
